server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:diarydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

app:
  jwt:
    secret: "replace-with-very-long-random-32bytes-minimum-secret"
    expiry: 604800000 # 7 days in ms
